package launcher

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"golang.org/x/term"

	"shop_bot/internal/config"
)

var ErrConfigExists = errors.New("configuration already exists")

type InitOptions struct {
	EnvPath  string
	In       io.Reader
	Out      io.Writer
	Verifier TelegramVerifier
}

type InitResult struct {
	Created  bool
	EnvPath  string
	Identity BotIdentity
}

func DefaultInitOptions() InitOptions {
	return InitOptions{
		EnvPath:  ".env",
		In:       os.Stdin,
		Out:      os.Stdout,
		Verifier: NewTelegramClient(10 * time.Second),
	}
}

// RunInit creates the smallest runnable configuration. An existing .env is
// treated as an idempotent success and is never changed.
func RunInit(ctx context.Context, opts InitOptions) (InitResult, error) {
	opts = normalizeInitOptions(opts)
	result := InitResult{EnvPath: opts.EnvPath}

	if info, err := os.Lstat(opts.EnvPath); err == nil {
		if !info.Mode().IsRegular() {
			return result, errors.New("configuration path exists but is not a regular file")
		}
		fmt.Fprintf(opts.Out, "[OK] %s already exists; kept unchanged.\n", opts.EnvPath)
		return result, nil
	} else if !os.IsNotExist(err) {
		return result, fmt.Errorf("inspect configuration: %w", err)
	}

	fmt.Fprintln(opts.Out, "Telegram Shop Bot Setup")
	fmt.Fprintln(opts.Out, "Two answers create a private, ready-to-check configuration.")
	fmt.Fprintln(opts.Out)

	prompter := newPrompter(opts.In, opts.Out)
	token, err := prompter.secret("BotFather token: ")
	if err != nil {
		return result, fmt.Errorf("read BotFather token: %w", err)
	}
	token = strings.TrimSpace(token)
	if err := config.ValidateBotToken(token); err != nil {
		return result, fmt.Errorf("invalid BotFather token: %w", err)
	}

	identity, err := opts.Verifier.Verify(ctx, token)
	if err != nil {
		return result, ErrTelegramCheck
	}
	fmt.Fprintf(opts.Out, "[OK] Telegram identity: @%s\n", identity.Username)
	if !identity.SupportsInlineQueries {
		fmt.Fprintln(opts.Out, "[TIP] Enable Inline Mode in @BotFather (/setinline) to share catalog products in any chat.")
	}

	fmt.Fprintln(opts.Out, "Tip: @userinfobot can show your numeric Telegram user ID.")
	adminRaw, err := prompter.text("Your Telegram user ID (admin): ")
	if err != nil {
		return result, fmt.Errorf("read admin ID: %w", err)
	}
	adminID, err := strconv.ParseInt(strings.TrimSpace(adminRaw), 10, 64)
	if err != nil || config.ValidateAdminUserID(adminID) != nil {
		return result, errors.New("invalid admin ID: enter your positive numeric Telegram user ID")
	}

	content := renderEnv(token, identity.Username, adminID)
	baseDir := filepath.Dir(opts.EnvPath)
	if err := ensurePrivateDir(filepath.Join(baseDir, "data")); err != nil {
		return result, err
	}
	if err := ensurePrivateDir(filepath.Join(baseDir, "backups")); err != nil {
		return result, err
	}
	if err := writeFileExclusiveAtomic(opts.EnvPath, []byte(content)); err != nil {
		return result, err
	}

	result.Created = true
	result.Identity = identity
	fmt.Fprintf(opts.Out, "[OK] Private configuration created: %s\n", opts.EnvPath)
	fmt.Fprintln(opts.Out, "[NEXT] Run `telegram-shop-bot doctor` or start the bot.")
	return result, nil
}

func normalizeInitOptions(opts InitOptions) InitOptions {
	defaults := DefaultInitOptions()
	if opts.EnvPath == "" {
		opts.EnvPath = defaults.EnvPath
	}
	if opts.In == nil {
		opts.In = defaults.In
	}
	if opts.Out == nil {
		opts.Out = defaults.Out
	}
	if opts.Verifier == nil {
		opts.Verifier = defaults.Verifier
	}
	return opts
}

func renderEnv(token, username string, adminID int64) string {
	return fmt.Sprintf(`# Generated by telegram-shop-bot init. Advanced settings use safe defaults.
BOT_TOKEN=%s
BOT_USERNAME=%s
ADMIN_IDS=%d
`, token, username, adminID)
}

func ensurePrivateDir(path string) error {
	if info, err := os.Lstat(path); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("protect %s: symbolic links are not accepted", path)
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("inspect %s: %w", path, err)
	}
	if err := os.MkdirAll(path, 0o700); err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	if err := os.Chmod(path, 0o700); err != nil {
		return fmt.Errorf("protect %s: %w", path, err)
	}
	return nil
}

func writeFileExclusiveAtomic(path string, content []byte) error {
	dir := filepath.Dir(path)
	file, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temporary configuration: %w", err)
	}
	tempPath := file.Name()
	defer os.Remove(tempPath)

	closeWithError := func(current error) error {
		if closeErr := file.Close(); current == nil && closeErr != nil {
			return closeErr
		}
		return current
	}
	if err := file.Chmod(0o600); err != nil {
		return closeWithError(fmt.Errorf("protect temporary configuration: %w", err))
	}
	if _, err := file.Write(content); err != nil {
		return closeWithError(fmt.Errorf("write temporary configuration: %w", err))
	}
	if err := file.Sync(); err != nil {
		return closeWithError(fmt.Errorf("sync temporary configuration: %w", err))
	}
	if err := closeWithError(nil); err != nil {
		return fmt.Errorf("close temporary configuration: %w", err)
	}

	// Linking is an atomic no-clobber publish: unlike Rename it cannot replace
	// a configuration created concurrently by another process.
	if err := os.Link(tempPath, path); err != nil {
		if os.IsExist(err) {
			return ErrConfigExists
		}
		return fmt.Errorf("publish configuration atomically: %w", err)
	}
	_ = os.Remove(tempPath)
	if err := syncDirectory(dir); err != nil {
		return fmt.Errorf("sync configuration directory: %w", err)
	}
	return nil
}

func syncDirectory(path string) error {
	// Directory fsync is not portable to Windows.
	if runtime.GOOS == "windows" {
		return nil
	}
	dir, err := os.Open(path)
	if err != nil {
		return err
	}
	defer dir.Close()
	return dir.Sync()
}

type prompter struct {
	in     io.Reader
	out    io.Writer
	reader *bufio.Reader
}

func newPrompter(in io.Reader, out io.Writer) *prompter {
	return &prompter{in: in, out: out, reader: bufio.NewReader(in)}
}

func (p *prompter) secret(prompt string) (string, error) {
	if _, err := fmt.Fprint(p.out, prompt); err != nil {
		return "", err
	}
	if input, ok := p.in.(*os.File); ok && term.IsTerminal(int(input.Fd())) {
		secret, err := term.ReadPassword(int(input.Fd()))
		fmt.Fprintln(p.out)
		return string(secret), err
	}
	return p.readLine()
}

func (p *prompter) text(prompt string) (string, error) {
	if _, err := fmt.Fprint(p.out, prompt); err != nil {
		return "", err
	}
	return p.readLine()
}

func (p *prompter) readLine() (string, error) {
	line, err := p.reader.ReadString('\n')
	if err != nil {
		if errors.Is(err, io.EOF) && line != "" {
			return strings.TrimSuffix(line, "\r"), nil
		}
		return "", err
	}
	return strings.TrimSuffix(strings.TrimSuffix(line, "\n"), "\r"), nil
}
